export default {
  buttons: {},
  lang: 'en-US',
  followingToolbar: true,
  otherStaticBar: '',
  // toolbar
  toolbar: [
    ['formatBlockHeading', ['formatH1', 'formatH2', 'formatH3', 'formatH4', 'formatH5', 'formatH6']],
    ['formatBlock', ['formatPara', 'formatCode']],
    ['style', ['style']],
    ['font', ['bold', 'italic', 'underline', 'clear']],
    ['fontname', ['fontname']],
    ['fontsize', ['fontsize']],
    ['color', ['color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['table', ['table']],
    ['insert', ['link', 'picture', 'video', 'hr', 'comment', 'htmlify', 'textify', 'iframe']],
    ['view', ['fullscreen', 'codeview', 'help']]
  ],
  // popover
  popatmouse: true,
  popover: {
    image: [
      ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
      ['float', ['floatLeft', 'floatRight', 'floatNone']],
      ['imagesLink', ['openMedia', 'saveMedia', 'copyMediaLink']],
      ['remove', ['removeMedia']]
    ],
    link: [
      ['link', ['linkDialogShow', 'unlink', 'copyLink']],
      ['remove', ['removeLink']]
    ],
    table: [
      ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
      ['delete', ['deleteRow', 'deleteCol', 'deleteTable']]
    ],
    air: [
      ['color', ['color']],
      ['font', ['bold', 'underline', 'clear']],
      ['para', ['ul', 'paragraph']],
      ['table', ['table']],
      ['insert', ['link', 'picture']]
    ]
  },
  // air mode: inline editor
  airMode: false,
  enableAirPopover: false,
  width: null,
  height: null,
  linkTargetBlank: true,
  focus: false,
  tabSize: 4,
  styleWithSpan: true,
  shortcuts: true,
  textareaAutoSync: true,
  hintDirection: 'bottom',
  tooltip: 'auto',
  container: 'body',
  maxTextLength: 0,
  clearEnterFormat: false, // 記得要改成false
  showHeadingLabel: false, // 記得要改成false
  enableDropImage: true,
  enablePasteImage: true,
  enableStatusbar: true,
  enableScrollVerticalCenter: true,
  enableTypeWriterSoundEffect: true,
  toolbarPosition: 'top',
  allowEnter: true,
  helpFooter: null,
  blockquoteBreakingLevel: 2,
  styleTags: ['p', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
  fontNames: [
    'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New',
    'Helvetica Neue', 'Helvetica', 'Impact', 'Lucida Grande',
    'Tahoma', 'Times New Roman', 'Verdana'
  ],
  fontSizes: ['8', '9', '10', '11', '12', '14', '18', '24', '36'],
  // pallete colors(n x n)
  colors: [
    ['#000000', '#424242', '#636363', '#9C9C94', '#CEC6CE', '#EFEFEF', '#F7F7F7', '#FFFFFF'],
    ['#FF0000', '#FF9C00', '#FFFF00', '#00FF00', '#00FFFF', '#0000FF', '#9C00FF', '#FF00FF'],
    ['#F7C6CE', '#FFE7CE', '#FFEFC6', '#D6EFD6', '#CEDEE7', '#CEE7F7', '#D6D6E7', '#E7D6DE'],
    ['#E79C9C', '#FFC69C', '#FFE79C', '#B5D6A5', '#A5C6CE', '#9CC6EF', '#B5A5D6', '#D6A5BD'],
    ['#E76363', '#F7AD6B', '#FFD663', '#94BD7B', '#73A5AD', '#6BADDE', '#8C7BC6', '#C67BA5'],
    ['#CE0000', '#E79439', '#EFC631', '#6BA54A', '#4A7B8C', '#3984C6', '#634AA5', '#A54A7B'],
    ['#9C0000', '#B56308', '#BD9400', '#397B21', '#104A5A', '#085294', '#311873', '#731842'],
    ['#630000', '#7B3900', '#846300', '#295218', '#083139', '#003163', '#21104A', '#4A1031']
  ],
  // http://chir.ag/projects/name-that-color/
  colorsName: [
    ['Black', 'Tundora', 'Dove Gray', 'Star Dust', 'Pale Slate', 'Gallery', 'Alabaster', 'White'],
    ['Red', 'Orange Peel', 'Yellow', 'Green', 'Cyan', 'Blue', 'Electric Violet', 'Magenta'],
    ['Azalea', 'Karry', 'Egg White', 'Zanah', 'Botticelli', 'Tropical Blue', 'Mischka', 'Twilight'],
    ['Tonys Pink', 'Peach Orange', 'Cream Brulee', 'Sprout', 'Casper', 'Perano', 'Cold Purple', 'Careys Pink'],
    ['Mandy', 'Rajah', 'Dandelion', 'Olivine', 'Gulf Stream', 'Viking', 'Blue Marguerite', 'Puce'],
    ['Guardsman Red', 'Fire Bush', 'Golden Dream', 'Chelsea Cucumber', 'Smalt Blue', 'Boston Blue', 'Butterfly Bush', 'Cadillac'],
    ['Sangria', 'Mai Tai', 'Buddha Gold', 'Forest Green', 'Eden', 'Venice Blue', 'Meteorite', 'Claret'],
    ['Rosewood', 'Cinnamon', 'Olive', 'Parsley', 'Tiber', 'Midnight Blue', 'Valentino', 'Loulou']
  ],
  foreColors: [],
  foreColorsName: [],
  backColors: [],
  backColorsName: [],
  enableCustomColors: true,
  lineHeights: ['1.0', '1.2', '1.4', '1.5', '1.6', '1.8', '2.0', '3.0'],
  tableClassName: 'table table-bordered',
  insertTableMaxSize: {
    col: 10,
    row: 10
  },
  backgroundColorButtons: {
    'backgroundColorRed': 'rgb(250, 136, 161)',
    'backgroundColorYellow': 'rgb(255, 239, 98)',
    'backgroundColorGreen': 'rgb(231, 244, 161)',
    'backgroundColorBlue': 'rgb(176, 223, 250)',
    'backgroundColorPurple': 'rgb(205, 197, 244)',
  },
  dialogsInBody: false,
  dialogsFade: false,
  toolbarAlign: 'center',
  toolbarSize: null,
  toolbarOverflow: false,
  toolbarCompact: false,
  maxHeight: null,
  maximumImageFileSize: null,
  callbacks: {
    onInit: null,
    onFocus: null,
    onBlur: null,
    onBlurCodeview: null,
    onEnter: null,
    onKeyup: null,
    onKeydown: null,
    onInput: null,
    onImageUpload: null,
    onImageUploadError: null,
    onImageLinkInsert: null
  },
  codemirror: {
    mode: 'text/html',
    htmlMode: true,
    lineNumbers: true
  },
  keyMap: {
    pc: {
      'ENTER': 'insertParagraph',
      'CTRL+Z': 'undo',
      'CTRL+Y': 'redo',
      //'TAB': 'tab',
      //'SHIFT+TAB': 'untab',
      'CTRL+B': 'bold',
      'CTRL+I': 'italic',
      'CTRL+U': 'underline',
      'CTRL+SHIFT+S': 'strikethrough',
      'CTRL+M': 'comment',
      'CTRL+S': 'saveHTML',
      'CTRL+ALT+M': 'uncomment',
      'CTRL+ALT+H': 'htmlify',
      'CTRL+ALT+T': 'textify',
      //'CTRL+SHIFT+E': 'comment',
      'CTRL+BACKSLASH': 'removeFormat',
      //'CTRL+SHIFT+L': 'justifyLeft',
      //'CTRL+SHIFT+E': 'justifyCenter',
      //'CTRL+SHIFT+R': 'justifyRight',
      //'CTRL+SHIFT+J': 'justifyFull',
      'CTRL+SHIFT+NUM7': 'insertUnorderedList',
      'CTRL+SHIFT+NUM8': 'insertOrderedList',
      'CTRL+LEFTBRACKET': 'outdent',
      'CTRL+RIGHTBRACKET': 'indent',
      'SHIFT+TAB': 'outdent',
      'TAB': 'indent',
      'CTRL+NUM0': 'formatPara',
      'CTRL+NUM1': 'formatH1',
      'CTRL+NUM2': 'formatH2',
      'CTRL+NUM3': 'formatH3',
      'CTRL+NUM4': 'formatH4',
      'CTRL+NUM5': 'formatH5',
      'CTRL+NUM6': 'formatH6',
      'CTRL+ENTER': 'insertHorizontalRule',
      'CTRL+K': 'linkDialog.show',
      'CTRL+L': 'linkDialog.show',
      'CTRL+BACKSPACE': 'removeElement',
    },
    mac: {
      'ENTER': 'insertParagraph',
      'CMD+Z': 'undo',
      'CMD+SHIFT+Z': 'redo',
      //'TAB': 'indent',
      //'SHIFT+TAB': 'untab',
      'SHIFT+TAB': 'outdent',
      'TAB': 'indent',
      'CMD+B': 'bold',
      'CMD+I': 'italic',
      'CMD+U': 'underline',
      'CMD+S': 'saveHTML',
      'CMD+SHIFT+S': 'strikethrough',
      'CMD+M': 'comment',
      'CMD+BACKSLASH': 'removeFormat',
      //'CMD+SHIFT+L': 'justifyLeft',
      //'CMD+SHIFT+E': 'justifyCenter',
      //'CMD+SHIFT+R': 'justifyRight',
      //'CMD+SHIFT+J': 'justifyFull',
      'CMD+BACKSPACE': 'removeElement',
      'CMD+SHIFT+NUM7': 'insertUnorderedList',
      'CMD+SHIFT+NUM8': 'insertOrderedList',
      'CMD+LEFTBRACKET': 'outdent',
      'CMD+RIGHTBRACKET': 'indent',
      'CMD+NUM0': 'formatPara',
      'CMD+NUM1': 'formatH1',
      'CMD+NUM2': 'formatH2',
      'CMD+NUM3': 'formatH3',
      'CMD+NUM4': 'formatH4',
      'CMD+NUM5': 'formatH5',
      'CMD+NUM6': 'formatH6',
      'CMD+ENTER': 'insertHorizontalRule',
      'CMD+K': 'linkDialog.show'
    }
  },
  icons: {
    'align': 'note-icon-align',
    'alignCenter': 'note-icon-align-center',
    'alignJustify': 'note-icon-align-justify',
    'alignLeft': 'note-icon-align-left',
    'alignRight': 'note-icon-align-right',
    'rowBelow': 'note-icon-row-below',
    'colBefore': 'note-icon-col-before',
    'colAfter': 'note-icon-col-after',
    'rowAbove': 'note-icon-row-above',
    'rowRemove': 'note-icon-row-remove',
    'colRemove': 'note-icon-col-remove',
    'indent': 'note-icon-align-indent',
    'outdent': 'note-icon-align-outdent',
    'arrowsAlt': 'note-icon-arrows-alt',
    'arrowsCircleDown': 'note-icon-arrow-circle-down',
    'arrowsCircleLeft': 'note-icon-arrow-circle-left',
    'arrowsCircleRight': 'note-icon-arrow-circle-right',
    'arrowsCircleUp': 'note-icon-arrow-circle-up',
    'bold': 'note-icon-bold',
    'caret': 'note-icon-caret',
    'circle': 'note-icon-circle',
    'close': 'note-icon-close',
    'code': 'note-icon-code',
    'copy': 'note-icon-code',
    'eraser': 'note-icon-eraser',
    'font': 'note-icon-font',
    'frame': 'note-icon-frame',
    'italic': 'note-icon-italic',
    'link': 'note-icon-link',
    'unlink': 'note-icon-chain-broken',
    'magic': 'note-icon-magic',
    'menuCheck': 'note-icon-menu-check',
    'minus': 'note-icon-minus',
    'orderedlist': 'note-icon-orderedlist',
    'pencil': 'note-icon-pencil',
    'picture': 'note-icon-picture',
    'question': 'note-icon-question',
    'redo': 'note-icon-redo',
    'square': 'note-icon-square',
    'strikethrough': 'note-icon-strikethrough',
    'comment': 'note-icon-pencil',
    'uncomment': 'note-icon-pencil',
    'htmlify': 'note-icon-pencil', // 錯誤的圖示
    'textify': 'note-icon-pencil', // 錯誤的圖示
    'subscript': 'note-icon-subscript',
    'superscript': 'note-icon-superscript',
    'table': 'note-icon-table',
    'textHeight': 'note-icon-text-height',
    'trash': 'note-icon-trash',
    'underline': 'note-icon-underline',
    'undo': 'note-icon-undo',
    'unorderedlist': 'note-icon-unorderedlist',
    'video': 'note-icon-video',
    'removeElement': 'note-icon-video'
  },
  KEY_MAP: {
      'BACKSPACE': 8,
      'TAB': 9,
      'ENTER': 13,
      'SPACE': 32,
      'DELETE': 46,
      // Arrow
      'LEFT': 37,
      'UP': 38,
      'RIGHT': 39,
      'DOWN': 40,
      // Number: 0-9
      'NUM0': 48,
      'NUM1': 49,
      'NUM2': 50,
      'NUM3': 51,
      'NUM4': 52,
      'NUM5': 53,
      'NUM6': 54,
      'NUM7': 55,
      'NUM8': 56,
      // Alphabet: a-z
      'B': 66,
      'E': 69,
      'H': 72,
      'I': 73,
      'J': 74,
      'K': 75,
      'L': 76,
      'M': 77,
      'R': 82,
      'S': 83,
      'U': 85,
      'V': 86,
      'X': 88,
      'Y': 89,
      'Z': 90,
      'SLASH': 191,
      'LEFTBRACKET': 219,
      'BACKSLASH': 220,
      'RIGHTBRACKET': 221,
      'ESC': 27
  },
  eventsWillApplyToElement: [
    'bold', 'italic', 'underline', 'strikethrough', 'removeFormat'
  ],
  scrollVerticalCenterSkipKeyCode: [
    33,34,35,36,37,38,39,40,45,112,113,114,115,116,117,118,119,120,121,122,123,27,9,20,16,17,18,144,145,19,93,91,92,24,25,8, 27, 8, 91, 16, 17, 18
  ],
  inlineElements: [
    "a","abbr","acronym","b","bdo","big","br","button","cite","code","dfn","em","i","img","input","kbd","label","map","object","output","q","samp","script","select","small","span","strong","sub","sup", "strike","textarea","time","tt","var"
  ],
  debug: {
    preventPopoverHide: false
  }
}